# Generated by Django 4.2.4 on 2023-08-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0002_tag_alter_post_options_alter_post_id_alter_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tagName',
            new_name='name',
        ),
    ]
